src/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)



"""
Authorization Flask Login

"""


# Login route
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email') 
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Log in successful!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.all_todos'))
            else:
                flash('Incorrect password, please try again!', category='error')
        else:
            flash('Email does not exists.', category='error') 


    return render_template('login.html', user=current_user)


# Signup route
@auth.route('/signup', methods=['GET','POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email') 
        first_name = request.form.get('firstName')
        last_name = request.form.get('lastName')
        password1 = request.form.get('password1') 
        password2 = request.form.get('password2') 
        
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exist.', category='error')    
        elif password1 != password2:
            flash('Passwords do not match, please try again', category='error')
            return redirect(url_for('auth.signup'))
        else:
            new_user = User(first_name=first_name, last_name=last_name, email=email, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()           
            flash('Success! Account created. Please login.', category='success')
            return redirect(url_for('auth.login'))

    return render_template('signup.html', user=current_user)


# Logout route
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

src/views.py
from flask import Blueprint, flash, redirect, render_template, url_for, request
from .models import Todo, Contact
from flask_login import login_required, current_user
from . import db
import datetime as dt


views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template('login.html', user=current_user)

"""
Contacts Views
"""

@views.route('/contacts')
def all_contacts():
    return render_template('contacts.html', user=current_user)


@views.route('/addcontact', methods=['POST','GET'])
def add_contact():
    employer = request.form.get('employer')
    title = request.form.get('title')
    date_iso = request.form.get('date')
    print('THIS IS DATE', type(date_iso), date_iso)
    if date_iso == '':
            date_iso = dt.datetime.now().isoformat(' ')
            print('THIS IS THE OTHER DATE', type(date_iso), date_iso)
    date = dt.datetime.fromisoformat(date_iso)
    print('THIS IS TODAY DATE', date)
    platform = request.form.get('platform')
    salary = request.form.get('salary')
    point_of_contact = request.form.get('point-of-contact')
    comments = request.form.get('comments')
    new_contact = Contact(employer=employer, title=title, date_applied=date, platform=platform, salary=salary, point_of_contact=point_of_contact, comments=comments, user=current_user)
    if request.method ==  'POST':
        db.session.add(new_contact)
        db.session.commit()
        return redirect(url_for('views.all_contacts'))
    else:
        return render_template('add_contact.html', user=current_user, new_contact=new_contact)




@views.route('/contactmoreinfo')
def more_info():
    return render_template('moreinfo_contact.html', user=current_user)



"""
To-do Views
"""

# All task with user route
@views.route('/todos')
@login_required
def all_todos():
    if current_user.is_authenticated:
        complete_task = Todo.query.filter_by(complete=True).all()
        tasks = Todo.query.all()
        return render_template('index.html', tasks=tasks, complete_task = complete_task, user=current_user)

        
# Add task with user route
@views.route('/add', methods=['POST'])
@login_required
def add_task():
    user_id = current_user.id
    task = request.form.get('content')
    due_date_iso = request.form.get('dueDate')
    if due_date_iso == '':
        due_date_iso = dt.datetime.now().isoformat(' ')
    due_date = dt.datetime.fromisoformat(due_date_iso)

    new_task = Todo(task=task, due_date=due_date, user_id=user_id)
    if task == "":
        flash('Please enter a task', category='error')
        redirect('/')
    else:
        db.session.add(new_task)
        db.session.commit()
    return redirect(url_for('views.all_todos'))


# Update task with user route 
@views.route('/update/<int:id>', methods=['POST', 'GET'])
@login_required
def update_task(id):
    update_id = Todo.query.get_or_404(id)
    if request.method == 'POST':
        update_id.task = request.form['content']
        if update_id.user_id == current_user.id:
            db.session.commit()
            return redirect(url_for('views.all_todos'))
          
    else:
        return render_template('update.html', update_id=update_id, user=current_user)


# Delete task route
@views.route('/delete/<int:id>')
@login_required
def delete_task(id):
    task_delete = Todo.query.get_or_404(id)
    if task_delete:
        db.session.delete(task_delete)
        db.session.commit()
        return redirect(url_for('views.all_todos'))


# Completed task route
@views.route('/complete/<int:id>', methods=['GET'])
@login_required
def completed_task(id):
    todo = Todo.query.get_or_404(id)
    todo.complete = True
    db.session.add(todo)
    db.session.commit()
    return redirect(url_for('views.all_todos'))

src/templates/add_contact.html
{% extends 'base.html' %}

{% block body %}

<div class="container card mt-5">
    <h3 class="mt-3">Add Contact</h3>

    <form action="{{ url_for('views.add_contact') }}" method="POST" class="input-group mb-3">
        <!-- employer -->

        <div class="input-group mb-3 mr-3 ml-3">
            <div class="input-group-prepend">
                <span class="input-group-text list-group-item list-group-item-light"
                    id="inputGroup-sizing-default">Employer</span>
            </div>
            <input name="employer" type="text" class="form-control list-group-item list-group-item-info"
                aria-label="Default" aria-describedby="inputGroup-sizing-default">
        </div>

        <!-- Title -->

        <div class="input-group mb-3 mr-3 ml-3">
            <div class="input-group-prepend">
                <span class="input-group-text list-group-item list-group-item-light"
                    id="inputGroup-sizing-default">Title</span>
            </div>
            <input name="title" type="text" class="form-control list-group-item list-group-item-info"
                aria-label="Default" aria-describedby="inputGroup-sizing-default">
        </div>

        <!-- Date -->

        <div class="input-group mb-3 mr-3 ml-3">
            <div class="input-group-prepend">
                <span class="input-group-text list-group-item list-group-item-light" id="inputGroup-sizing-default">Date
                    Applied</span>
            </div>

            <input name="date" type="date" class="form-control list-group-item list-group-item-info"
                aria-label="Default" aria-describedby="inputGroup-sizing-default">

        </div>



        <!-- Platform -->

        <div class="input-group mb-3 mr-3 ml-3">
            <div class="input-group-prepend">
                <span class="input-group-text list-group-item list-group-item-light"
                    id="inputGroup-sizing-default">Platform</span>
            </div>
            <input name="platform" type="text" class="form-control list-group-item list-group-item-info"
                aria-label="Default" aria-describedby="inputGroup-sizing-default">
        </div>

        <!-- Remote -->
        <!-- 
        <div class="input-group mb-3 mr-3 ml-3">
            <div class="input-group-prepend">
                <span class="input-group-text list-group-item list-group-item-light"
                    id="inputGroup-sizing-default">Remote</span>
            </div>
            <div type="text" class="form-control list-group-item list-group-item-info" aria-label="Default"
                aria-describedby="inputGroup-sizing-default">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="remoteYes" id="inlineRadio1" value="option1">
                    <label class="form-check-label" for="inlineRadio1">Yes</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="remoteNo" id="inlineRadio2" value="option2">
                    <label class="form-check-label" for="inlineRadio2">No</label>
                </div>
            </div>
        </div> -->

        <!-- Salary -->

        <div class="input-group mb-3 mr-3 ml-3">
            <div class="input-group-prepend">
                <span class="input-group-text list-group-item list-group-item-light"
                    id="inputGroup-sizing-default">Salary</span>
            </div>
            <input name="salary" type="text" class="form-control list-group-item list-group-item-info"
                aria-label="Default" aria-describedby="inputGroup-sizing-default">
        </div>

        <!-- Point of contact -->

        <div class="input-group mb-3 mr-3 ml-3">
            <div class="input-group-prepend">
                <span class="input-group-text list-group-item list-group-item-light"
                    id="inputGroup-sizing-default">Point of
                    Contact</span>
            </div>
            <input name="point-of-contact" type="text" class="form-control list-group-item list-group-item-info"
                aria-label="Default" aria-describedby="inputGroup-sizing-default">
        </div>

        <!-- Comments -->

        <div class="input-group mb-3 mr-3 ml-3">
            <div class="input-group-prepend">
                <span class="input-group-text">Comments</span>
            </div>
            <textarea name="comments" class="form-control" aria-label="With textarea"></textarea>
            <!-- <input name="comments" class="form-control" aria-label="With textarea"> -->

        </div>

        <input type="submit" class="btn btn-primary mb-2 ml-3">
        <a href="{{ url_for('views.all_contacts')}}" class="btn btn-primary mb-2 ml-1">Back</a>

    </form>
</div>

{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head %}{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='img') }}">
    <script src="https://kit.fontawesome.com/66a3cb6240.js" crossorigin="anonymous"></script>

</head>

<!-- Navbar -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <div class="navbar-brand" href="#"> </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav d-flex align-items-center">
                {% if current_user.is_authenticated %}
                <div class="" style="color: rgb(243, 200, 11)"><b>Hello, {{user.first_name}}</b> </div>
                <!-- <a class="nav-item nav-link active" href="{{ url_for('views.all_todos')}}">Home<span
                        class="sr-only">(current)</span></a> -->
                <a class="nav-item nav-link active" href="{{ url_for('views.all_todos')}} ">To-Do List</a>
                <a class="nav-item nav-link active" href="{{ url_for('views.all_contacts')}} ">Contacts</a>
                <a class="nav-item nav-link" href="{{ url_for('auth.logout')}} ">Logout</a>

                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('auth.login')}} ">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('auth.signup')}} ">Signup</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>
<!-- end -->

<body>

    <!-- Flask flash messages -->

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, msg in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{msg}}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% else %}

    <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{msg}}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}

    <!-- End of flash messages -->

    {% block body %}


    {% endblock %}

    <!-- Script tags -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/index.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

src/templates/contacts.html
{% extends 'base.html' %}

{% block body %}

<div class="container-fluid mt-5">
    <div class="d-flex justify-content-center">
        <a href="{{ url_for('views.add_contact')}}">
            <button type="button" class="btn btn-primary">Add Contact</button>
        </a>
    </div>
    <div class="d-flex justify-content-between flex-column m">
        <div class="card mt-3 mr-auto">
            <div class="card-body">
                <h5 class="card-title">Two Fish Creative</h5>

                <ul class="list-group">

                    <!-- Title -->

                    <li class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text list-group-item list-group-item-light"
                                id="inputGroup-sizing-default">Title</span>
                        </div>
                        <div type="text" class="form-control list-group-item list-group-item-info" aria-label="Default"
                            aria-describedby="inputGroup-sizing-default">Software Engineer Python</div>
                    </li>

                    <!-- Date -->

                    <li class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text list-group-item list-group-item-light"
                                id="inputGroup-sizing-default">Date Applied</span>
                        </div>
                        <div type="text" class="form-control list-group-item list-group-item-info" aria-label="Default"
                            aria-describedby="inputGroup-sizing-default">04/02/2021</div>
                    </li>
                </ul>

                <!-- Buttons -->

                <a href="{{ url_for('views.more_info')}}" class="btn btn-primary">More Info</a>
                <a href="#" class="btn btn-primary">Edit</a>
                <a href="#" class="btn btn-danger" style="float: right;">Delete</a>
            </div>
        </div>
        <div class="card mt-3 mr-auto">
            <div class="card-body">
                <h5 class="card-title">Two Fish Creative</h5>

                <ul class="list-group">

                    <!-- Title -->

                    <li class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text list-group-item list-group-item-light"
                                id="inputGroup-sizing-default">Title</span>
                        </div>
                        <div type="text" class="form-control list-group-item list-group-item-info" aria-label="Default"
                            aria-describedby="inputGroup-sizing-default">Software Engineer Python</div>
                    </li>

                    <!-- Date -->

                    <li class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text list-group-item list-group-item-light"
                                id="inputGroup-sizing-default">Date Applied</span>
                        </div>
                        <div type="text" class="form-control list-group-item list-group-item-info" aria-label="Default"
                            aria-describedby="inputGroup-sizing-default">04/02/2021</div>
                    </li>
                </ul>

                <!-- Buttons -->

                <a href="{{ url_for('views.more_info')}}" class="btn btn-primary">More Info</a>
                <a href="#" class="btn btn-primary">Edit</a>
                <a href="#" class="btn btn-danger" style="float: right;">Delete</a>
            </div>
        </div>
    </div>

</div>

{% endblock %}

src/templates/index.html
{% extends 'base.html' %}

{% block head %}

Todo App

{% endblock %}


{% block body %}


<!-- Input field -->

<div class="container d-flex flex-column content">
    <h1 class="d-flex d-flex justify-content-center">To-do List</h1>

    <form class="d-flex justify-content-between p-2 mb-4" action="{{ url_for('views.add_task') }}" method="POST">
        <input class="form-control" type="text" name="content" id="content" placeholder="Enter a new task and due date">
        <input class="calendar ml-3" type="date" id="dueDate" name="dueDate">
        <input class="btn btn-primary ml-3" type="submit" value="Add Task" id="aqua">
    </form>

    <!-- Table header -->

    <div class="list">
        <div class="list-group list-group-flush">
            <div class="list-group-item" id="heading__color">
                <div class="row">
                    <div class="col-sm">
                        <h6>Pending</h6>
                    </div>
                    <div class="col-sm">
                        <h6>Task</h6>
                    </div>
                    <div class="col-sm">
                        <h6>Due</h6>
                    </div>
                    <div class="col-sm">
                        <h6>Actions</h6>
                    </div>
                </div>
            </div>
        </div>

        <!-- Todo list content -->

        <ul class="list-group">
            {% for task in user.todos %}
            {% if task.complete == false %}

            <li class="list-group-item list-group-item-action list-group-item-info" id="babyblue">
                <div class="row d-flex align-items-center">
                    <div class="col-sm">
                        <label for="minusBox">
                            <a href="{{ url_for('views.completed_task', id=task.id)}}">
                                <i class="far fa-minus-square fa-lg text-danger"></i>
                            </a>
                        </label>
                    </div>
                    <div class="col-sm">
                        <label for="{{ task.user.id }}" id="check">{{
                            task.task
                            }}</label>
                    </div>
                    <div class="col-sm">
                        {{ task.due_date.date().strftime("%m/%d/%y") }} </div>
                    <div class="col-sm d-flex align-items-center justify-content-between">
                        <a href="/update/{{task.id}}" class="btn btn-primary btn-sm" id="aqua"><i
                                class="fas fa-pencil-alt"></i></a>
                        <a class="up" href="#"><i class="fas fa-arrow-circle-up fa-2x"></i></a>
                        <a class="down" href="#"><i class="fas fa-arrow-circle-down fa-2x"></i></a>
                    </div>

                </div>

            </li>
            {% endif %}
            {% endfor %}
        </ul>
    </div>

    <!-- Completed task list header -->

    <h4 class="d-flex d-flex justify-content-start mt-5"> <u>Completed Task</u> </h4>
    <div class="list">
        <ul class="list-group list-group-flush">
            <li class="list-group-item" id="heading__color">
                <div class="row">
                    <div class="col-sm">
                        <h6>Status</h6>
                    </div>
                    <div class="col-sm">
                        <h6>Task</h6>
                    </div>
                    <div class="col-sm">
                        <h6>Added</h6>
                    </div>
                    <div class="col-sm">
                        <h6>Due</h6>
                    </div>
                    <div class="col-sm">
                        <h6>Actions</h6>
                    </div>
                </div>
            </li>
        </ul>

        <!-- Todo list complete task  -->

        <ul class="list-group">
            {% for task in user.todos %}
            {% if task.complete == true %}
            <li class="list-group-item list-group-item-action list-group-item-info" id="salmon">

                <div class="row d-flex align-items-center">
                    <div class="col-sm">
                        <div class="text-success"> <i class="far fa-check-square fa-lg"></i>
                        </div>
                    </div>
                    <div class="col-sm">
                        <div id="completed">{{ task.task }}</div>
                    </div>
                    <div class="col-sm">
                        <div id="completed">{{ task.date_created.date().strftime("%m/%d/%Y") }}</div>
                    </div>
                    <div class="col-sm">
                        <div id="completed">{{ task.due_date.date().strftime("%m/%d/%Y") }}</div>
                    </div>
                    <div class="col-sm d-flex align-items-center">
                        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal"
                            data-target="#delete{{ task.id }}">
                            <i class="far fa-trash-alt"></i>
                        </button>
                    </div>
                </div>

            </li>
            {% endif %}
            {% endfor %}
        </ul>
    </div>

    <!-- Modal -->

    {% for task in user.todos %}
    {% if task.complete == true %}

    <div class="modal fade" id="delete{{ task.id }}" tabindex="-1" role="dialog"
        aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Delete Task</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h5 class="text-danger"> Are you sure you want to delete this task?
                    </h5>
                </div>
                <div class="modal-footer">
                    <a type="button" class="btn btn-primary" href="{{ url_for('views.delete_task', id=task.id)}}">
                        Ok</a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}

    {% endblock %}

src/templates/login.html
{% extends 'base.html' %}

{% block body %}


<div class="container-fluid">
    <div class="row no-gutter">
        <!-- The image half -->
        <div class="col-md-6 d-none d-md-flex bg-image"></div>


        <!-- The content half -->
        <div class="col-md-6 bg-light">
            <div class="login d-flex align-items-center py-5">

                <!-- Content-->
                <div class="container">
                    <div class="row">
                        <div class="col-lg-10 col-xl-7 mx-auto">
                            <h3 class="display-4">Login</h3>
                            <p class="text-muted mb-4">Please enter your login information</p>
                            <form action="{{ url_for('auth.login') }}" method="POST">

                                <div class="form-group mb-3">
                                    <input name="email" id="email" type="email" placeholder="Email address" required=""
                                        autofocus="" class="form-control rounded-pill border-0 shadow-sm px-4">
                                </div>
                                <div class="form-group mb-3">
                                    <input name="password" id="password" type="password" placeholder="Password"
                                        required=""
                                        class="form-control rounded-pill border-0 shadow-sm px-4 text-primary">
                                </div>
                                <button type="submit"
                                    class="btn btn-primary btn-block text-uppercase mb-2 rounded-pill shadow-sm">Sign
                                    in</button>
                                <div class="text-center d-flex justify-content-between mt-4">
                                    <p>Don't have a login? <a href="{{ url_for('auth.signup') }}"
                                            class="font-italic text-muted">
                                            <u class="tes">Signup</u></a></p>
                                </div>
                            </form>
                        </div>
                    </div>
                </div><!-- End -->
            </div>
        </div><!-- End -->
    </div>
</div>

{% endblock %}

src/templates/signup.html
{% extends 'base.html' %}

{% block body %}



<div class="container-fluid">
    <div class="login d-flex align-items-center py-5">

        <!--Content-->

        <div class="container">
            <div class="row"></div>
            <div class="row">
                <div class="col-lg-10 col-xl-7 mx-auto">
                    <h3 class="display-4">Sign up</h3>
                    <p class="text-muted mb-4">Please enter your information</p>
                    <form action="{{ url_for('auth.signup') }}" method="POST">
                        <div class="form-group mb-3">
                            <input name="email" id="email" type="email" placeholder="Email address" required=""
                                autofocus="" class="form-control rounded-pill border-0 shadow-sm px-4">
                        </div>
                        <div class="form-group mb-3">
                            <input name="firstName" id="firstName" type="text" placeholder="First Name" required=""
                                autofocus="" class="form-control rounded-pill border-0 shadow-sm px-4">
                        </div>
                        <div class="form-group mb-3">
                            <input name="lastName" id="lastName" type="text" placeholder="Last Name" required=""
                                autofocus="" class="form-control rounded-pill border-0 shadow-sm px-4">
                        </div>
                        <div class="form-group mb-3">
                            <input name="password1" id="password1" type="password" placeholder="Password" required=""
                                class="form-control rounded-pill border-0 shadow-sm px-4 text-primary">
                        </div>
                        <div class="form-group mb-3">
                            <input name="password2" id="password2" type="password" placeholder="Confirm Password"
                                required="" class="form-control rounded-pill border-0 shadow-sm px-4 text-primary">
                        </div>
                        <button type="submit"
                            class="btn btn-primary btn-block text-uppercase mb-2 rounded-pill shadow-sm">Sign
                            in</button>
                        <div class="text-center d-flex justify-content-between mt-4">
                            <p>Already registered? <a href="{{ url_for('auth.login') }}" class="font-italic text-muted">
                                    <u>Login</u></a></p>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- End -->

    </div>
</div>

{% endblock %}

src/templates/update.html
{% extends 'base.html' %}

{% block head %}

Todo App

{% endblock %}


{% block body %}

<!-- Update task  -->

<div class="content">
    <h1 class="d-flex d-flex justify-content-center">Update Task</h1>

    <div class="container d-flex flex-column content">
        <form class="d-inline-flex p-2" action="{{ url_for('views.update_task', id=update_id.id)}}" method="POST">
            <input class="form-control" type="text" name="content" id="content" value="{{update_id.task}}">
            <input class="btn btn-primary ml-3" class="btn btn-primary" type="submit" value="Update" id="aqua">
        </form>
    </div>
</div>
{% endblock %}